server {
    listen 80;

    # Send API calls to Spring Boot
    location /api/ {
        proxy_pass http://api:8080/api/;
    }

    # Serve React files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
