spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hireme
    username: hireme
    password: hireme
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
